#!/usr/bin/env bash
# write-launchers.sh — emit per-claude-pane launch-*.sh wrappers into manifest dir.
#
# Called AFTER handoff extraction (which writes handoff-*.md), BEFORE write-manifest.py
# (which validates launcher paths in its output).
#
# Each launcher is a self-contained shell script that:
#   1. Cd's into the captured cwd
#   2. Exec's `claude` with the handoff text as its first user message
#
# Why a launcher script vs inlining `claude "$(cat ...)"` in tmux send-keys: avoids all
# shell-escaping concerns. The handoff content is read from disk by the launcher; tmux
# only sees a clean script path.
#
# Usage:
#   write-launchers.sh <manifest_dir> <inventory_json_path> <claude_binary_path>
#
# Output: NDJSON to stdout, one line per launcher written:
#   {"pane":"<S:W.P>","launcher":"<abs_path>","handoff":"<rel_path>"}
#
# Exit codes:
#   0 = all launchers written
#   1 = bad args
#   2 = referenced handoff missing for a claude pane (write-manifest.py will also catch this)

set -uo pipefail

MANIFEST_DIR="${1:?usage: write-launchers.sh <manifest_dir> <inventory_json> <claude_binary>}"
INVENTORY_JSON="${2:?missing inventory json path}"
CLAUDE_BIN="${3:?missing claude binary path}"

if [ ! -d "$MANIFEST_DIR" ]; then
    echo "ERROR: manifest dir does not exist: $MANIFEST_DIR" >&2
    exit 1
fi

if [ ! -f "$INVENTORY_JSON" ]; then
    echo "ERROR: inventory JSON not found: $INVENTORY_JSON" >&2
    exit 1
fi

python3 - "$MANIFEST_DIR" "$INVENTORY_JSON" "$CLAUDE_BIN" <<'PYEOF'
import json
import os
import stat
import sys

manifest_dir = sys.argv[1]
inventory_path = sys.argv[2]
claude_bin = sys.argv[3]

with open(inventory_path) as f:
    inv = json.load(f)


def pane_key(session, window_index, pane_index):
    safe_session = session.replace('/', '-').replace(' ', '_')
    return f"{safe_session}-{window_index}-{pane_index}"


missing = []
written = []

for w in inv.get('windows', []):
    for p in w.get('panes', []):
        if p.get('claude_pid') is None:
            continue  # not a claude pane
        session = w['session']
        wi = w['window_index']
        pi = p['pane_index']
        key = pane_key(session, wi, pi)
        handoff_rel = f"handoff-{key}.md"
        handoff_full = os.path.join(manifest_dir, handoff_rel)
        if not os.path.exists(handoff_full):
            missing.append(f"{session}:{wi}.{pi} → {handoff_rel}")
            continue

        launcher_rel = f"launch-{key}.sh"
        launcher_full = os.path.join(manifest_dir, launcher_rel)
        cwd = p.get('cwd') or p.get('pane_path') or os.path.expanduser('~')

        # shlex.quote for proper POSIX shell escaping (handles spaces, quotes, etc.)
        import shlex
        cwd_q = shlex.quote(cwd)
        bin_q = shlex.quote(claude_bin)
        handoff_q = shlex.quote(handoff_rel)
        content = (
            "#!/bin/bash\n"
            "# Auto-generated by /restart-process — restores a fresh claude session\n"
            "# with the captured handoff as the first user message.\n"
            "set -e\n"
            f"cd {cwd_q} 2>/dev/null || cd ~\n"
            f"HANDOFF=\"$(dirname \"$0\")/{handoff_rel}\"\n"
            "if [ ! -r \"$HANDOFF\" ]; then\n"
            f"    echo \"ERROR: handoff missing: $HANDOFF\" >&2\n"
            f"    exec {bin_q}\n"
            "fi\n"
            # Pass handoff content as first argument to claude
            f"exec {bin_q} \"$(cat \"$HANDOFF\")\"\n"
        )

        # Atomic write
        tmp = launcher_full + '.tmp'
        with open(tmp, 'w') as f:
            f.write(content)
            f.flush()
            os.fsync(f.fileno())
        os.chmod(tmp, stat.S_IRWXU | stat.S_IRGRP | stat.S_IROTH | stat.S_IXGRP | stat.S_IXOTH)
        os.rename(tmp, launcher_full)

        written.append({
            "pane": f"{session}:{wi}.{pi}",
            "launcher": launcher_full,
            "handoff": handoff_rel,
        })

for entry in written:
    print(json.dumps(entry))

if missing:
    print(f"ERROR: missing handoff files for {len(missing)} claude panes:", file=sys.stderr)
    for m in missing:
        print(f"  {m}", file=sys.stderr)
    sys.exit(2)

print(f"wrote {len(written)} launcher scripts", file=sys.stderr)
PYEOF
